### ISSUE TITLE
danger notification get's success green background

### ISSUE THREAD

**Issue by zilahir** [teodosii/react-notifications-component#13] opened 2019-02-05 09:32 UTC
`const` variables: 

```
const ERROR = 'DANGER';
const NO_NAME = 'You must provide a name for this calculation!'
```

```
addNotification(title, message, type) {
        this.notificationDOMRef.current.addNotification({
          title: title,
          message: message,
          type: type.toLowerCase(),
          insert: "top",
          container: "top-right",
          animationIn: ["animated", "fadeIn"],
          animationOut: ["animated", "fadeOut"],
          dismiss: { duration: 2500 },
          dismissable: { click: true }
        });
      }
```

```
this.addNotification(ERROR, NO_NAME, ERROR)
```

<img width="309" alt="danger_error" src="https://user-images.githubusercontent.com/6687149/52264160-a800a500-2939-11e9-8288-e736380647b7.png">

**Comment by teodosii** [comment] 2019-02-05 19:14
Couldn't reproduce, pretty sure you've messed somehow the styles. Tested in the `samples` project, replaced `TypeExample.js`'s `add` with this piece of code and it's working as expected

```jsx
add() {
  const ERROR = 'DANGER';
  const NO_NAME = 'You must provide a name for this calculation!';
  return this.props.addNotification({
    title: ERROR,
    message: NO_NAME,
    type: ERROR.toLowerCase(),
    insert: "top",
    container: "top-right",
    animationIn: ["animated", "fadeIn"],
    animationOut: ["animated", "fadeOut"],
    dismiss: { duration: 2500 },
    dismissable: { click: true }
  });
}
```

**Comment by teodosii** [comment] 2019-02-07 14:33
Did you manage to fix the issue or is it still reproducing @zilahir ? Without a reproducing repo I cannot really reproduce this as it's working as expected in the samples project - which is the source code for github pages.

**Comment by zilahir** [comment] 2019-02-07 14:35
@teodosii i did a small hack to be honest: 

```
.notification-danger {
    .notification-message {
        background-color: $warning-text-color !important;
        text-align: left;
    }
}
```

I did not have time to create a sandbox project and try to reproduce it, so went around the problem myself. Thanks for the reply and the question tho, during the weekend i'll try to reproduce myself in a clean project and see where does that leads.

**Comment by teodosii** [comment] 2019-02-08 11:08
I'd suggest you to use custom content as it is a better suit if you want more control over the CSS. I will close this issue for now, feel free to open another issue if you struggle with it or you find another bug.

**Closed by teodosii** 2019-02-08 11:08 UTC
