### ISSUE TITLE
Multiple notifications make last notification unable to dismiss

### ISSUE THREAD

**Issue by andergabilondo** [teodosii/react-notifications-component#44] opened 2019-12-23 09:30 UTC
When more than 20 notifications arrive without dismissing any of them, the last one remains, unable to dismiss.

To test it:

`const notificationInterval = setInterval(
  () =>
    storeNotification.addNotification({
      title: 'Wonderful!',
      message: 'teodosii@react-notifications-component',
      type: 'success',
      insert: 'top',
      container: 'top-right',
      animationIn: ['animated', 'fadeIn'],
      animationOut: ['animated', 'fadeOut'],
      dismiss: {
        duration: 0,
        onScreen: false
      }
    }),
  1000
);

setTimeout(() => {
  clearInterval(notificationInterval);
}, 22000)`

Thanks for the job, the component is awesome

**Comment by andergabilondo** [comment] 2019-12-23 09:43
Here comes an update. The problem appears when you dismiss them quickly. The onRemoval function does not execute but the notifications are graphically dismissed. The result is a notification that is not possible to remove.

**Comment by teodosii** [comment] 2019-12-23 12:10
I tried on GitHub pages and I was not able to reproduce. You're saying `onRemoval` is not being executed but your example do not have any `onRemoval` callback. Could you record your screen while doing this? As gif would help. Or provide an example that I'll be able to reproduce it each time, otherwise I cannot help you.

I double checked the handling for dismissal and it's always checking updating the previous state which should always result in correct dismissal.

**Comment by andergabilondo** [comment] 2019-12-23 17:33
![Fail](https://user-images.githubusercontent.com/38155124/71371311-0154df80-25b1-11ea-8708-05e08c4e1a54.gif)

Hello,
I have tried to reproduce the issue with the github pages. I achieved it partially,

The problem comes in the mobile device emulation. I created a console.log with a counter that prints on every dismiss. If you click fast in the first notification before the transition completes, the onRemoval action is not executed.

`let counter = 0;
...
      onRemoval: () => {
        console.log(counter);
        counter++;
      },`

In my code (haven't found the reason yet), the result is shown in the gif. The notifications are fixed and unable to remove.

Thanks for your support!

**Comment by teodosii** [comment] 2019-12-23 18:05
Thank you for details, will look into it but most likely will get fixed after New Year

**Comment by teodosii** [comment] 2020-03-14 16:23
I've tried reproducing this bug but it didn't happen to me. Not even once. Could you have a look again at that? I really don't know what would be causing this as I tried manually spamming notifications and each of them gets closed afterwards. Will close it for now and I'm waiting for your answer.

**Closed by teodosii** 2020-03-14 16:23 UTC
