### ISSUE TITLE
Notification with dismiss, get frozen and doesn't dismiss

### ISSUE THREAD

**Issue by MohamedLamineAllal** [teodosii/react-notifications-component#18] opened 2019-03-27 23:30 UTC
An issue  that will be a bug, is noticed. Notification freeze, and doesn't dismiss. Neither does with on click.
Here the config
```
this.defaultConfig = {
            insert: 'top',
            container: 'top-right',
            animationIn: ["animated", "flipInX"],
            animationOut: ["animated", "flipOutY"],
            dismiss: { duration: 8000 },
            dismissable: { click: true }
        }
```
Keeping happening.  The phenomena is seen when multiple notification happen at same time. One of them freeze.

**Comment by teodosii** [comment] 2019-03-28 18:04
That is weird, did the console show any error or warning whatsoever? I've tried reproducing that with CRA and didn't happen even once. All notifications dismissed after 8s or if they were manually dismissed before. I've also run a performance check but it's not telling me anything.

Anyway, I don't recommend doing this way. Use staggering for multiple notifications, considering this one uses flip which is sort of heavy animation to the eye.

**Comment by MohamedLamineAllal** [comment] 2019-03-31 21:20
Thank you for the quick response. Sorry for being late. I think it may be related to the re-rendering and the state. I'm using Redux. And i have a login implementation, with expiring session, and auto-logout. This phenomena happen when the logout is triggered, and the login page show. I'm sorry. but i was wrong. The problem is not related to multiple notification. There was a problem before. About multiple notification. I created a function to add a notification at an interval rate. So it's not my problem. And i have seen that this was fixed. 

So this problem maybe related to the state and the re-rendering. It keep happening (my solution was to set my own timer and force dismiss using removeNotification, which seem to work). Here an image that show that. The notification is forzen. Click dismiss not working. And for the console no errors, clicking or not. The screenshot bellow show all that:
![Screenshot from 2019-03-31 22-09-23](https://user-images.githubusercontent.com/20062543/55295235-9f40c280-5402-11e9-8171-92efd385b203.png)
![Screenshot from 2019-03-31 22-09-32](https://user-images.githubusercontent.com/20062543/55295237-a1a31c80-5402-11e9-8f8a-bcae3fb1c46e.png)
![Screenshot from 2019-03-31 22-10-37](https://user-images.githubusercontent.com/20062543/55295238-a536a380-5402-11e9-8386-3a37099574be.png)

I hope this will help. When i get time i may check this out myself.

**Comment by teodosii** [comment] 2019-04-04 06:55
You are free to do any pull requests to this project as long as the PR is properly written and tested. Are you using custom content or custom X on that notification? Or is it the default success type without any additional custom things? There's definitely an issue there but have no clue at the moment what would be causing this as I cannot reproduce it. I will let this open, maybe others face this issue as well and have a reproducing repo.

**Comment by MohamedLamineAllal** [comment] 2019-04-04 22:06
Thank you again. for the question, it's the default one. No custom. When i get anything i will let you know.

**Comment by teodosii** [comment] 2019-04-23 14:18
Closing it for now as it cannot be reproduced on my side. If others face the same issue and have some specific steps in order to reproduce it, then I'll provide a fix.

**Closed by teodosii** 2019-04-23 14:18 UTC
Labels: bug

**Comment by maro84** [comment] 2019-05-15 07:38
I had the same problem - last notification didn't dismiss. I imported the `animate.css` and it works! 
Thanks [@bobdeei](https://github.com/teodosii/react-notifications-component/issues/21#issuecomment-485160736)

**Comment by kishan143-jaiswal** [comment] 2019-11-23 05:16
same issue arrised in my project  toaster got frozen , even after timeout is not getting dead and as suggested by @maro84  . i also imported animate.css and its worked for now but using of animate.css of 3000+ lines is worthless for just toaster frozen issue.
need some alternate solution for this.
